modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ssblur/scriptor_mana/issues"
license = "CC0-1.0"

[[mods]]
modId = "scriptor_mana"
version = "${version}"
displayName = "Scriptor Magicae: Mana Mode"
authors = "SSBlur"
description = '''
An addon for Scriptor that replaces the default cooldown system with a mana bar.
'''
logoFile = "icon.png"

[[dependencies.scriptor_mana]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor_mana]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor_mana]]
modId = "unfocused"
type = "required"
versionRange = "[${unfocused_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "scriptor_mana.mixins.json"
